[package]
name = "advent-of-code-rust"
version = "0.2020.0"
authors = ["Carlos Macasaet <rust-developer@carlos-m.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
